### ISSUE TITLE
cannot work "smartAutomorphism"

### ISSUE THREAD

**Issue by K-miran** [homenc/HElib#101]
As far as I remember, I used "smartAutomorphism" function one year ago, but it does not work any more in this HElib library version. When I run the same code, I have 

Ctxt.cpp:945: void Ctxt::smartAutomorph(long int): Assertion `pubKey.isReachable(k,keyID)' failed.
Aborted (core dumped)

I would appreciate if someone response this problem. 

p.s. I used the simple automorphism function instead. However, if I do that, I have a problem that it cannot support multiplication between the ciphertext (after automorphism) and the other ciphertext. Is it right that there is no key-switching matrix for it?

**Comment by shaih** [comment]
Did you remember to "`addSome1DMatrices`" after generating the keys?

**Comment by K-miran** [comment]
Thank you for the quick response. 

Of couse, I wrote "addSomelDMatrices" after generating public and secret keys.

**Comment by fionser** [comment]
@K-miran, `addSome1DMatrices` just add a part of the switching matrices into the public key.
You need to figure out what automorphisms you need. You might try `addAllMatrices` too see whether it work. If it work, which mean besides `addSome1DMatrices` you need to add more extra switching matrices.

**Comment by K-miran** [comment]
@fionser, "addAllMatrices" works well even though it takes longer than "addSome1DMatrices". Thank you very much for the comment.

**Comment by fionser** [comment]
@K-miran。 Yes, `addAllMatrices` generates all the possible switching matrices for you thus, it should take much longer that `addSome1DMatrices`.
