### ISSUE TITLE
How to read the timing

### ISSUE THREAD

**Issue by mohakamo** [homenc/HElib#104]
I've two questions;
- Firstly, when I print the timing, I got the following results.  
  
  DoubleCRT: 3.60079 / 1152 = 0.00312569   [DoubleCRT.cpp:354]
  FFT: 3.598 / 2304 = 0.00156163   [CModulus.cpp:191]
  FFT: 3.59861 / 1152 = 0.00312379   [DoubleCRT.cpp:90]
  FFT_remainder: 0.43445 / 2304 = 0.000188563   [CModulus.cpp:196]
  MyFunction: 6.7345 / 1 = 6.7345   [FheSearch.cpp:331]
  iFFT: 1.66679 / 1152 = 0.00144687   [CModulus.cpp:244]
  iFFT_division: 0.618747 / 1152 = 0.000537107   [CModulus.cpp:294]
  modDownToSet: 6.34904 / 128 = 0.0496019   [Ctxt.cpp:172]
  operator*=: 6.72669 / 128 = 0.0525523   [Ctxt.cpp:696]
  toPoly: 2.31808 / 1152 = 0.00201223   [DoubleCRT.cpp:677]
  
  The root is the MyFunction. I know that MyFunction's total timing is 6.7..
  But the total timing of the listed functions overpass this time. Something wrong here?
- Secondly, each multiplication requires a modDownToSet, can we eliminate this?

**Comment by fionser** [comment]
@mohakamo For the first question, the answer is that 
the timing is not exclusive, some parts of the timings also include
the timing of other functions;

For the second question, I don't think it work, personally.

**Comment by faberga** [comment]
Closed as answered.
