### ISSUE TITLE
how to recrypt a cipher and get a new cipher under another pk

### ISSUE THREAD

**Issue by Maridy** [homenc/HElib#107]
hello,
I'm currrently learning on FHE and HElib, but I got some problems with the recryption. I generate two keys pk1 pk2 with same params just as the operation in  the Test_bootstrap.cpp file, then encrypt m1,m2 and get ciphertext c1,c2 , c1=encrypt(m1,pk1),c2=encrypt(m2,pk2).
 I can use  void FHEPubKey::reCrypt(Ctxt &ctxt) to recrypt cipher under the same key, such as 
 c1 \* = c1; pk1.reCrypt(c1); 
and can't just do add or mul on c1 c2,like c1+=c2;c1 \* = c2.
but is it possible to recrypt like that: pk2.reCrypt(c1,encrypt(sk1,pk2)), and get the cipher c1 under pk2, then do c1+=c2.
Correct me if I'm wrong.
In advance, many thanks.

**Comment by waleed092** [comment]
Looking for the answer of the Same  above question ????

**Comment by shaih** [comment]
Why do you use two keys, what's wrong with using just one? HElib does not implement bootstrapping from one key to another, though I imagine that adding this will not be very hard as long as they are using the same parameters.

But note that if you publish some information that let's you bootstrap from pk1 to pk2, then you can use the secret-key of pk2 to decrypt messages that were encrypted using pk1. Why would you want this?
