### ISSUE TITLE
What's the use of findM?

### ISSUE THREAD

**Issue by antoniolm23** [homenc/HElib#108]
Hi, 
I saw a code where the method findM is not used, I'm wondering if this method is needed or I can skip it and I can generate the context directly in this way: 

`FHEcontext context(32, 1031, 1);`

Moreover if I don't use findM, could I have a security issue in my code? 

Thanks in advance

**Comment by faberga** [comment]
Thanks to @olimasters - Yes, you can specify m directly without using findM.  You can check what security level this gives by calling context.securityLevel().
