### ISSUE TITLE
Can HElib support OpenMP?

### ISSUE THREAD

**Issue by rzxvv** [homenc/HElib#112]
Hello guys
I am a newcomer to HElib, but currently have a C++ project with OpenMP
My question is simple.
Can I use OpenMP to HElib?

**Comment by NanXiao** [comment]
Yes. Because both HElib and NTL can be compiled in thread-safe version, so you can use OpenMP over it.

**Comment by faberga** [comment]
As @NanXiao said, HElib and NTL can be compiled in thread-safe. But neither HElib or NTL are OpenMP aware, meaning they will not make use of the OpenMP thread pool. NTL implements its own thread pool which you may use in a way that HElib+NTL are aware.
