### ISSUE TITLE
How can I encrypt a file?

### ISSUE THREAD

**Issue by wilsonalberto-git** [homenc/HElib#17]
Hi everyone,  I am interesting in HElib, I downloaded and Installed, also I followed the demo, and everything is ok. Now, I just wanted to know how I can encrypt a file (for instance: txt, doc, or xls) and modified in the encrypted domain by using HElib. As I see in the sample code, it is used a plaintextArray, but I do not really know how can I covert a file (txt, doc or xls) into plaintextArray.

Thank you for your help.

**Comment by onesiess** [comment]
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "Findhelib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "helib", but
  CMake did not find one.

  Could not find a package configuration file provided by "helib" (requested
  version 2.2.0) with any of the following names:

    helibConfig.cmake
    helib-config.cmake

  Add the installation prefix of "helib" to CMAKE_PREFIX_PATH or set
  "helib_DIR" to a directory containing one of the above files.  If "helib"
  provides a separate development package or SDK, be sure it has been
  installed.
it happened when i run the examples,can you tell me how should slove it? thank you very much
