### ISSUE TITLE
Q: Plaintext polanomial encode

### ISSUE THREAD

**Issue by boev** [homenc/HElib#283]
From what I understand, a plaintext polynomial is instance of zz_pX. Such zz_pX instance can be encrypted the following way: 
```
secretKey.Encrypt(Ctxt, conv<ZZX>(zz_pX));
```
How can I encode a long of my choosing into such zz_pX instance? I have seen the example where a random polynomial is encoded into zz_pX, but I want to encode my own long plaintext valus as polynom and do calculation in the Ring of polynomials mod phimX where:
```
zz_pXModulus phimX = conv<zz_pX>(ea.getPAlgebra().getPhimX());
```
I cannot seem to find an easy encode method for this, help is much appreciated. Basically I want to encode a long valued -> do calculation with it in the plaintext polynom ring, change it -> then encrypt it and do calculation in encrypted form.

**Comment by shaih** [comment]
If you want to encrypt a single long in its own ciphertext then one way to do it would be
```
secretKey.Encrypt(Ctxt, conv<ZZX>(long));
```
Note that when you decry pt that ciphertext you would get long mod p, where p is the plaintext modulus.

As an aside, encrypting a single long in its own ciphertext will be very inefficient for most usage cases

**Comment by boev** [comment]
Thanks, all this is working. I cannot explain/understand inverting this encoding or ctxt. If I initialize with p=2 and r=16 for example. Then my question would be:
1.  For a even number a (example a = 12) I cannot compute the inverse mod 2^16. It does not exist.
2. If I encode 12 as polynom zz_pX can I invert it against my mod 2^16 also encoded? (I think this is not possible, for the same reason)
3. If I encrypt 12 as **ctxt**, here I should be able to compute inverse **ctxt_inv** against my cyclotomic polynomial, because I am in a Ring. And decrypt(ctxt*ctxt_inv) should give me 1 mod 2^16.

Is (3) correct and is there a way to compute this in HElib?
