### ISSUE TITLE
CMake with Visual Studio 2017 on Windows 10

### ISSUE THREAD

**Issue by jamesdang** [homenc/HElib#298]
When I tried to CMake HELib with Visual Studio 2017, I got the following error:

CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  GMP required dynamic shared library has not been found.  (Try cmake
  -DGMP_DIR=<GMP-root-path>).  (missing: GMP_LIB GMP_HEADERS) (Required is at
  least version "6.0.0")

Please help!

**Comment by fionser** [comment]
install gmp and set the GMP_DIR like "cmake -DGMP_DIR = XXXX"

**Comment by faberga** [comment]
Dear James,

The HElib has only been developed and tested on Linux and Mac OS.
It has not been tested or it is supported on Windows 10.

**Comment by jamesdang** [comment]
Thank you @fionser and @faberga. I'll try on Mac.
