### ISSUE TITLE
Can Helib has can implement  a Ctxt divided by two?

### ISSUE THREAD

**Issue by Ldisi** [homenc/HElib#299]
**Your Contact:** 
**Your environment (OS/HW):**
**Detailed Description:**
Such as, m1 = [2], implement m1/2 = [1], Is there such function?

**Comment by ssmiler** [comment]
You can do it by changing plaintext space from 2^r to 2^(r-1), look [https://github.com/homenc/HElib/blob/master/src/Test_extractDigits.cpp](here)

**Comment by Ldisi** [comment]
thanks, but the operation "dividend by two" is not easy to realize,am i right?

**Comment by ssmiler** [comment]
You are right for plaintext spaces mod p where p>2. In the binary case it's
easy.

**Comment by Ldisi** [comment]
Yes! My work is in plaintext spaces mod p where p >> 2, is there method to do that?

**Comment by ssmiler** [comment]
No efficient one as I know. You can express the div by 2 function as a
polynomial of degree log(p) evaluation. Usually it's costly

**Comment by Ldisi** [comment]
THX ^-^

**Comment by shaih** [comment]
If your plaintext space is an odd number p, then divide-by-two is the same as multiplying by (p+1)/2.

**Comment by Ldisi** [comment]
Thanks,you are right.But it still seems difficult to implement (p+1)/2.

**Comment by shaih** [comment]
it's not difficult, just use ctxt.multByConstant(to_ZZ((p+1)/2))

**Comment by Ldisi** [comment]
THX！I will try it later




------------------ Original ------------------

**Comment by Ldisi** [comment]
You are right，I have tried it！




------------------ Original ------------------
