### ISSUE TITLE
Package Build errors

### ISSUE THREAD

**Issue by jamesdang** [homenc/HElib#304]
**Your Contact:** 
**Your environment (OS/HW): ubuntu 18.10**
**Detailed Description:**

I built with option 1: package build (recommended for most users). Here is my steps:

1,
cd HElib
mkdir build
cd build

2,
cmake -DPACKAGE_BUILD=ON -DCMAKE_INSTALL_PREFIX=/home/myname/helib_install ..

3, 
make -j16

I got errors here. Since I was in the empty directory of build, there was no 'make' here. Why should I enter this dir 'build'? Or should I copy something to this dir?

I then cd .. and ran 'make -j16'. After a long run I got these errors:

[ 91%] Performing build step for 'helib_external'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [CMakeFiles/helib_external.dir/build.make:111: dependencies/Stamp/helib_external/helib_external-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/helib_external.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
 
Any help would be appreciated.

James

**Comment by mayank26saxena** [comment]
Hey @jamesdang, how did you solve this?

**Comment by jamesdang** [comment]
Hi @mayank26saxena, the solution is to add ntl and gmp to the last line of CMakeLists.txt of helib_example:

target_link_libraries(helib_example helib gmp ntl)
