### ISSUE TITLE
What happens if the security-level < 0？

### ISSUE THREAD

**Issue by Ldisi** [homenc/HElib#308]
Hi!I am new to the new version. In helb_example.cpp m=32109, it runs slowly. So I change m to 4, it seem that pragrams runs much faster than before but security-level < 0. What happens if the security-level < 0？Does this mean the scheme is unsafe？

**Comment by boev** [comment]
Yes. I **think** m = 4 leaves us with very small polynomial ring and one could try different bruteforce approaches. Guessing the added error (including position where its added), would allow you to round and decrypt even without the secret key. And there are different ways to check if your decrypted result is correct. This work has helped me visualize RLWE encryption/decryption: https://blog.n1analytics.com/homomorphic-encryption-illustrated-primer/

**Comment by Ldisi** [comment]
THX！




------------------ Original ------------------

**Comment by shaih** [comment]
any security-level value less than 64 (including negative values) basically mean no security at all, there are easy attacks that will recover the secret decryption key from the public key. To get real security you need the security level to be above 100
