### ISSUE TITLE
How to use CKKS?

### ISSUE THREAD

**Issue by WangLuyao627** [homenc/HElib#332]
When I use decimals, I encrypt and decrypt, it is wrong, how to encrypt and decrypt?

**Comment by olimasters** [comment]
Please could you post the code that you wrote that resulted in the problem?  That way we can try to see if there are any errors.

**Comment by WangLuyao627** [comment]
I modified some code based on the previously written code，
“ EncryptedArrayCx ea(context, context.alMod.getCx());
  vector<double> vd1;
  vector<double> vd2;
  vd1.resize(ea.size(),0);
  vd2.resize(ea.size(),0);
  Ctxt c1(pk);
  ea.encrypt(c1, pk, vd1);
  ea.decrypt(c1, sk, vd2);  
  cout << vd2 <<endl;  "

This is part of my code,I changed p to -1and assigned value to vd1,But it was wrong to decrypt it.

**Comment by WangLuyao627** [comment]
> Please could you post the code that you wrote that resulted in the problem? That way we can try to see if there are any errors.

https://github.com/homenc/HElib/issues/332#issuecomment-561547407

> Please could you post the code that you wrote that resulted in the problem? That way we can try to see if there are any errors.



> Please could you post the code that you wrote that resulted in the problem? That way we can try to see if there are any errors.

I modified some code based on the previously written code, and made some attempts:
"  EncryptedArrayCx ea(context, context.alMod.getCx());
   vector<double> vd1;
   vector<double> vd2;
   vd1.resize(ea.size(),0);
   vd2.resize(ea.size(),0);
   Ctxt c1(pk);
   ea.encrypt(c1, pk, vd1);
   ea.decrypt(c1, sk, vd2);
   cout << vd2 << endl;  "

This is part of my code, I changed p to -1 and assigned value to vd1,But it was wrong to decrypt it.

**Comment by olimasters** [comment]
What parameters are you using?  I'm particularly interested in `bits` and `r`.

**Comment by WangLuyao627** [comment]
> What parameters are you using? I'm particularly interested in `bits` and `r` since if these are too low there's a good chance of errors.

I The parameters I set are as follows：
r = 8; L = 60; c = 2; w = 64; d = 0; k = 80;

**Comment by esteffin** [comment]
Hi, looking at the parameter you used I can see that `r` is quite low and this will affect the precision of the encoding.
Having `r = 50` will probably fix this issue.
Also I assume your `L` value indicates the number of `bits` of the modulus chain. If so its value is very small too. If you perform several multiplications the noise will grow too much affecting the decryption. You can try to increase it to `bits = 300` and see what happens. You can check the remaining bit capacity at any point by calling `Ctxt::bitCapacity`.
