### ISSUE TITLE
How can i perform addition between the slots of a Ctxt ? 

### ISSUE THREAD

**Issue by lupascucristian** [homenc/HElib#336]
**Your Contact:** clupascu8@gmail.com 
**Your environment (OS/HW):** Ubuntu 18.04.03 LTS
**Detailed Description:** Suppose we have a Ctxt with 84 slots, each one containing the encryption of 1/0 (in F2). How should we compute the sum (xor) of those slots ?

**Comment by boev** [comment]
You can use shifts and additions. The idea should be the same as in runningSums method in HElib (check [this](https://github.com/homenc/HElib/blob/master/src/EncryptedArray.cpp)). It is probably is better to use the native HElib method for this, than implementing your own.

**Comment by lupascucristian** [comment]
Thank you, Yordan !
