### ISSUE TITLE
About decimal precision.

### ISSUE THREAD

**Issue by WangLuyao627** [homenc/HElib#337]
In operations that support decimals, if the decimal is particularly small, even -2.6633e-20, it will affect the next operation. Why?

**Comment by esteffin** [comment]
Sorry, but I do not understand completely your question. Can you please explain what you mean when you say "it will affect the next operation"? Also could you post the code that you wrote that resulted in the problem? That way we can try to see if there are any errors.

I see that the number you are trying to encode is extremely small. To be sure it will not be affected too much by CKKS inherent noise, use an adequate `r` value.
