### ISSUE TITLE
Recrypt issue?

### ISSUE THREAD

**Issue by s-naveen** [homenc/HElib#418]
Why do I get a error when I add this line before decrypting for bootstrapping purposes.
`public_key.reCrypt(encrypted_text);`

`libc++abi.dylib: terminating with uncaught exception of type helib::LogicError: Decrypting with too much noise`

If I run without that line it works fine it seems odd that bootstrapping should reduce noise but actually increase it in this case? Can someone explain? 

params used: p=1523 m=10185 r=1 bits=500 c=2 gens = {7276, 6112, 6791} ords = {6, 4, 2}

**Comment by jlhcrawford** [comment]
Hi @s-naveen,

Bootstrapping does not cause the noise level to return to that of a freshly encrypted ciphertext. Therefore you are unable to perform the same number of operations after bootstrapping as you were prior to bootstrapping.

This paper has more details on how bootstrapping works: https://eprint.iacr.org/2014/873

You can also have a look at the bootstrapping benchmark located in `benchmarks/bgv_thinboot.cpp` for an example of bootstrapping.

**Comment by s-naveen** [comment]
@jlhcrawford thank you will read it up 🙂

**Comment by faberga** [comment]
Duplicate
EXC_BAD_ACCESS when calling recrypt method in v2.0.0 #419
