### ISSUE TITLE
looking forward to docs of bootstrapping

### ISSUE THREAD

**Issue by SpiriLiao** [homenc/HElib#43]
As title, I think many other people like me are eager for docs of bootstrapping, just like [he-library.pdf](https://github.com/shaih/HElib/tree/master/doc/designDocument).
thanks for your industrious work.

**Comment by fionser** [comment]
Here. Boostrapping for HElib http://eprint.iacr.org/2014/873.pdf

**Comment by SpiriLiao** [comment]
Long time to github,thanks

**Comment by faberga** [comment]
Closing - This is already resolved by fionser's comment.
