### ISSUE TITLE
How can I set my own key

### ISSUE THREAD

**Issue by KwonDK** [homenc/HElib#433]
Hello, I want to set my own secret key, but the function `GenSecKey()` cannot provide this.

For example, I try to set my secret key like `[1,0,1,0]` according to BGV (context : p=17, r=1, m=8). 

`helib::Context context = helib::ContextBuilder<helib::BGV>()`
`                                                  .m(m)`
`                                                  .p(p)`
`                                                  .r(r)`
`                                                  .bits(bits)`
`                                                  .c(c)`
`                                                  .build()`
`helib::SecKey secret_key(context);`
`secret_key.GenSecKey();`

I cannot input secret key [1,0,1,0] anywhere..

Does HElib support a secret key customizing?(like password) 
Is there any function that can provide a 'custom secret key'?

**Comment by faberga** [comment]
@KwonDK 
In HElib we don't support an API to customize keys like passwords. Key pairs are genearated based on the context parameters. Each key generation request generates a new key.

Please check the utilities provided in the [utils ](https://github.com/homenc/HElib/tree/master/utils) directory.

**Comment by KwonDK** [comment]
@faberga 
Thank you very much!
