### ISSUE TITLE
Where is the  document of HElib “user manual”

### ISSUE THREAD

**Issue by jzw9510** [homenc/HElib#440]
I need the HElib “user manual”, Can you provide me the user manual or download link ?

**Comment by faberga** [comment]
Hi @jzw9510 
The most recent API documentation is available at https://homenc.github.io/HElib/
and in the following papers:
https://eprint.iacr.org/2020/1481.pdf
https://eprint.iacr.org/2014/873.pdf
https://eprint.iacr.org/2018/244.pdf
https://eprint.iacr.org/2014/106.pdf

**Comment by faberga** [comment]
Closed as resolved.
