### ISSUE TITLE
To build on Mac m1

### ISSUE THREAD

**Issue by rvjansen** [homenc/HElib#468]
The clang compiler on the M1 macs does not like -march=native. This can be remedied by a 
```
set(PRIVATE_HELIB_CXX_FLAGS "-mcpu=lightning")
```
in the CmakeLists.txt file. This issue documents the change.

**Comment by fedejinich** [comment]
this helped me, but instead of using "mpcpu" I used 
```
set(PRIVATE_HELIB_CXX_FLAGS "-mcpu=apple-m1")
```
