### ISSUE TITLE
Build Installation Error

### ISSUE THREAD

**Issue by fanfan328** [homenc/HElib#476]
Hi, I have a problem on installing HElib, 
I'm using WSL2 run on Windows 10 system.

Also I have succeed installing NTL and the GMP without any problem. 
The problem is when I run **_"make -j16"_** command, it show some error with helib_external.

Already tried to using this solution but it seems not working. #304 

Command : make -j16

[  0%] Built target setup_install_dir
[ 33%] Built target gmp_fetched
[ 66%] Built target ntl_fetched
[ 66%] Built target dependencies_built
[ 70%] Performing build step for 'helib_external'
make[3]: *** No targets specified and no makefile found.  Stop.
make[2]: *** [CMakeFiles/helib_external.dir/build.make:112: dependencies/Stamp/helib_external/helib_external-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/helib_external.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I think the problem is in these command.
make -f CMakeFiles/helib_external.dir/build.make CMakeFiles/helib_external.dir/build

Any help would be appreciated.

**Comment by nxhieu3102** [comment]
Hi @fanfan328 , how u resolve it ?
