### ISSUE TITLE
Support for language bindings (Rust FFI, etc.)

### ISSUE THREAD

**Issue by ckrd-mark** [homenc/HElib#502]
Auto-generated FFI bindings greatly reduce the burden of keeping a 3rd party library up to date.  I'm exploring creating a Rust crate that binds to HElib.  It appears promising.

There are some utility functions that may assist creating a 'safer' Rust crate with low level access.  Would such additions be in scope?

To have a fully safe Rust crate would appear (at this early stage) to require more intrusive changes.  This will be known once I have several working examples.  Alternatively, the risky interfaces could be made private. Would such changes be in scope?

**Comment by faberga** [comment]
Hi @ckrd-mark, HElib is _not- being actively developed anymore. It is in limited maintenance mode, only for security bugs.
