### ISSUE TITLE
problems about  make fhe.a

### ISSUE THREAD

**Issue by xplittle** [homenc/HElib#62]
My OS CentOS6, and I have installed GMP and NTL correctly. But when I make fhe.a，it shows that
g++ -g -02 -c NumbTh.cpp
In file included from NumbTh.cpp 16:0
NumbTh.h:34;20;  "NTL/ZZ.h" there is no that file
# include<NTL/ZZ.h>

make termination 
make  ***[NUMBTH.o] error 1
I am looking forward your answers.  Thank you very much

**Comment by ssmiler** [comment]
g++ cannot find the NTL headers. Try to look for NTL headers in /usr/local/include/NTL or /usr/include/NTL, then you should add this path to CPLUS_INCLUDE_PATH environment variable, see http://www.network-theory.co.uk/docs/gccintro/gccintro_23.html for more details.

**Comment by faberga** [comment]
Closing.  Thanks to  @ssmiler for answering the question.

This should not be a problem if using the latest HElib installed as per instructions in INSTALL.md
