### ISSUE TITLE
Can HElib handle arbitrary length integers (GMP)?

### ISSUE THREAD

**Issue by t-ghost** [homenc/HElib#69]
Hi!

According to what I know from the documentation and the test examples, HElib does not seem to be able to use GMP integers (mpz_t) with arbitrary length in the encrypted arrays (those also with arbitrary length?) due to the polynomial structure and the modulus p^r. For an optimization of what I try to do, something like this would be great, but I think it is not supported by HElib (yet) or even by the encryption scheme itself - and it already sounds like being computationally intensive.
So, just to make sure:
Is there a way to use GMP numbers in HElib plaintext vectors? I only saw them being used with 'long' types.

Best,
Thomas

**Comment by fionser** [comment]
I am working to extend this limited plaintext space problem. What I am doing 
is to apply the Chinese Remainder Theorem(CRT). We can use several co-prime `p^r`,
and encrypt what you are going to encrypt for each of this `p^r` then do the evaluation.
The final result is obtained by applying the CRT.

**Comment by t-ghost** [comment]
That sounds great! I didn't think about using the CRT to do this... If I understand it correctly then this would solve the first of my two problems, which is the large numbers in the the encrypted arrays. The other one - unlimited length arrays - would still persist, if I am right. (Thanks for the idea to solve the first problem, though!)

**Comment by fionser** [comment]
Yes, currently, EncryptedArrary supports thousands of slots but not unlimited.
If you want to use a large number of slots, I recommend you to use multiple ciphertexts to
encode a large array.

**Comment by faberga** [comment]
Closing.

Thanks to @fionser for answering the question.
