### ISSUE TITLE
Please, produce a tutorial

### ISSUE THREAD

**Issue by murbard** [homenc/HElib#8]
I have a high level understanding of lattice encryption, I understand what homomorphic encryption achieves but I am not familiar enough with the details of the scheme to make sense of the doxygen documentation of this project. 

Please produce a HeLib tutorial that introduces the different classes and methods. To start with, how about a homomorphic 2+2=4 example?

**Comment by mominbuet** [comment]
[https://pwnhome.wordpress.com/2013/05/03/guide-to-helib-1/] was helpful!

**Comment by pradeepk1992** [comment]
Hi, 
I am sorry for interrupting but I can't find the Test_General.cpp file in Helib-master/src folder so please suggest me accordingly.
Thanks

**Comment by evbarnett** [comment]
Sorry to revive an old issue- does anyone know of a similar simple tutorial that explains doing simple arithmetic with bootstrapping? I'm having trouble understanding the tests. Thanks!
