### ISSUE TITLE
How to recrypt?

### ISSUE THREAD

**Issue by matlink** [homenc/HElib#80]
I'm trying to recrypt a ciphertext which is actually an integer (`p` is for example 1031). I have then two ciphertexts `c1` and `c2` that I multiply between them with `c1*=c2`. Depending on the maximum allowed depth, the warning `Ctxt::findBaseSet warning: already at lowest level` is prompted when noise is too big to decrypt correctly.

I've looked up a bit the `Test_bootstrap.cpp` file, however there are too many variables for me to understand exactly how to configure `FHEcontext`. I'm stuck with this kind of error : 
`EvalMap.cpp:176: AltStep1Matrix<type>::AltStep1Matrix(const EncryptedArray&, std::tr1::shared_ptr<CubeSignature>, const NTL::Vec<long int>&, long int, long int, bool, bool) [with type = PA_zz_p]: Assertion 'sz == reps.length()' failed` 
which I don't really understand.

I wonder if someone has a piece of code to show me how to recrypt a ciphertext and if possible with the bunch of variables used for the given code.

In advance, many thanks.

P.S : the tutorials and the documentation given by @shaih are quite out of date.

**Comment by shaih** [comment]
To be able to recrypt you must set the instance up as "bootstrappable", unfortunately this means that you need to set some variables to appropriate values.

> I've looked up a bit the Test_bootstrap.cpp file, however there are too
> many variables for me to understand exactly how to configure FHEcontext

Perhaps elaborate on this? What variables did you have problems with?

p.s. You can find another example of how to use recryption in the AES code under src/aes

**Comment by matlink** [comment]
In fact my main goal is to make everything to depend on the security parameter, let's say with a max circuit depth as around 10.

For example, instead of using polynomials in `Test_bootstrap.cpp`, is it possible to use `NewPlaintextArray` ?

**Comment by shaih** [comment]
> For example, instead of using polynomials in Test_bootstrap.cpp,
> is it possible to use NewPlaintextArray ?

Sure. But you would still need to find appropriate parameters for this value of p=1031 and whatever if your security parameter. In general bootstrapping scales very poorly with large p. This is why we never tested it with such large value, and why the example parameters in Test_boostrapping.cpp only go upto p=127.

You would probably get better results (at the cost of a more complex code) by working with smaller p (e.g., p^r=2^4=16, so you can use the parameters for p=2). You will need to write some code to manipulate the base-p^r digits of the big number that you have in the application.

**Comment by matlink** [comment]
Many thanks !

Is it possible to deduce the security parameter in function of the content of `mValues` (except `p`, in the `Test_bootstrapping.cpp` file), or the opposite, deduce `phi(m),  m, d, m1,  m2, m3, g1, g2, g3, ord1, ord2, ord3, c_m` in function of the security parameter ?

**Comment by shaih** [comment]
Deducing the security parameter from the other parameters is easy, just call `FHEcontext::securityLevel()`,

> or the opposite, deduce phi(m), m, d, m1, m2, m3, g1, g2, g3, ord1, ord2, ord3, c_m
> in function of the security parameter ?

I wish..

Finding all these parameters is currently a form of black art. Developing tool support for choosing parameters is a research project that I would love to engage in, if only I could find the time. If anyone else is willing to put serious research time in it, I will be more than happy to help.

There is a rudimentary tool for choosing parameters for bootstrapping, see `src/params.cpp` (or just `make params_x` and then `./params_x --help`). If you want to get parameters for a value of p as large as p=1031, then you probably need to use higher upper- and lower-bounds than the defaults, for example `./params_x p=1031 lo=20000 hi=150000`. (I never tried it with such large values, so let me know what you get if you try it.)

**Comment by matlink** [comment]
>  just call `FHEcontext::securityLevel()`

The number returned is always negative, I guess I should take the opposite as the security level, right ?

```
./params_x p=1031 lo=15000 hi=20000
phim= 12000  d=  40  m= 15005  k=-7.00366 m=(5)*{3001} :-( m/phim(m)=1.25 C=637 D=2 E=3 
phim=  5760  d=  30  m= 15015  k=-61.1276 m=3*5*7*(11)*{13} m/phim(m)=2.6 C=44 D=4 E=1 
phim=  9072  d=  18  m= 15093  k=-31.9665 m=(3^3)*{13}*43 m/phim(m)=1.66 C=70 D=2 E=1 
phim=  9504  d=  66  m= 15111  k=-27.4957 m=(3^2)*{23}*73 m/phim(m)=1.58 C=138 D=2 E=1 
phim=  8568  d=  42  m= 15141  k=-35.8331 m=(3)*{7^2}*103 m/phim(m)=1.76 C=144 D=2 E=1 
phim= 10368  d=  48  m= 15155  k=-20.712 m=5*(7)*{433} m/phim(m)=1.46 C=104 D=2 E=4 
phim=  9504  d=  72  m= 15219  k=-28.803 m=3^2*(19)*{89} m/phim(m)=1.6 C=98 D=2 E=3 
phim= 14976  d=  39  m= 15229  k=21.7274 m=97*(157) m/phim(m)=1.01 C=137 D=2 E=0 
phim= 15000  d=  50  m= 15251  k=20.9095 m=(101)*151 :-( m/phim(m)=1.01 C=201 D=3 E=1 
phim= 12960  d=  90  m= 15257  k=1.45634 m=(11)*{19}*73 m/phim(m)=1.17 C=162 D=2 E=1 
phim= 11760  d=  14  m= 15265  k=-7.64123 m=5*(43)*{71} m/phim(m)=1.29 C=226 D=2 E=1 
phim=  7200  d=  30  m= 15345  k=-47.1512 m=(3^2)*5*11*{31} m/phim(m)=2.13 C=48 D=3 E=1 
phim=  8064  d=  48  m= 15351  k=-40.7108 m=3*(7)*{17}*43 m/phim(m)=1.9 C=92 D=3 E=4 
phim=  7488  d=  78  m= 15405  k=-45.4588 m=(3)*5*13*{79} m/phim(m)=2.05 C=94 D=3 E=1
```

Except here, sometimes `k` is positive, sometimes not. When looking at how it is computed, it's a constant factor 7,2/`bitsize` of `phim` minus 110. Where do the 7,2 and 110 come from ?

**Comment by shaih** [comment]
> The number returned is always negative, I guess I should take its opposite as the security level, right?

No, you should assume security=0 in this case.My guess is that to get any real security with p=1031 you will need m to be at least in the 60000 to 80000 range, maybe more.

> Where do the 7,2 and 110 come from ?

Appendix C in http://eprint.iacr.org/2012/099

**Comment by matlink** [comment]
Many thanks !

Do you know if there is somewhere an implementation of the very first Gentry's scheme? Nor if this one is usable without all the improvements done afterwards?

**Comment by umikachen** [comment]
> My guess is that to get any real security with p=1031 you will need m to be at least in the 60000 to 80000 range, maybe more.  

In the reference, the equation 'N > (L(log N + 23) − 8.5)(k + 110)/7.2' only reveal the relation between k and m. 
And I ran Test_General with different p. To my surprise, with a larger p I get a smaller m. So how does the parameter p effect m in HElib? Did I get the right result(m)? Thank you.
```
1.  
$ ./Test_General_x dry=1 p=10131131 L=4
*** Bound N=4355, choosing m=4513, phi(m)=4512
******** TestIt(dry run): R=1, p=10131131, r=1, d=1, c=2, k=80, w=64, L=4, m=4513, gens=[], ords=[]
m = 4513, p = 10131131 (dry run)
2.  
$ ./Test_General_x dry=1 p=1031 L=4
*** Bound N=4355, choosing m=4591, phi(m)=4590
******** TestIt(dry run): R=1, p=1031, r=1, d=1, c=2, k=80, w=64, L=4, m=4591, gens=[], ords=[]
m = 4591, p = 1031 (dry run)
3.  
$ ./Test_General_x dry=1 p=2 L=4
*** Bound N=4355, choosing m=4859, phi(m)=4704
******** TestIt(dry run): R=1, p=2, r=1, d=1, c=2, k=80, w=64, L=4, m=4859, gens=[], ords=[]
m = 4859, p = 2 (dry run)
```

**Comment by shaih** [comment]
The larger p is, the faster the noise accumulates. The accumulation of noise grows more or less linearly with p, for example a multiply-by-constant operation increases the noise by a factor of about (p+sqrt(m)).

Moreover, the recryption-circuit itself grows somewhat deeper with larger p. So you get a deeper circuit, and each operation adding more noise, so you need many more levels to implement recryption. For example we get depth~12 when p=2, depth-28 for p=17, depth-21 for p=127 and depth-46 for p=256.

This, means that you have much larger L value, and therefore need much larger value of N in the equation above (for the same security parameter k), which translates to larger m.

**Comment by umikachen** [comment]
> For example we get depth~12 when p=2, depth-28 for p=17, depth-21 for p=127 and depth-46 for p=256.

So how did you get the right depth(L)? 

In a particular problem(circuit), I choose the L by testing:
```
1. decide p, k
2. choose one L by guess
3. use FindM to decide m and run the test
4. if I got the warning message "Ctxt::findBaseSet warning: 
     already at lowest level" I increase L, otherwise decrease it.
5. find the smallest L that meets the problem.
```
So does the parameter L and m I got in this way meet the security level k?

**Comment by ssmiler** [comment]
What you can do is to execute with large `L` and see the level of resulting ciphertexts using `findBaseLevel()`. Afterwards you decrease the initial `L` parameter by `findBaseLevel()-1`. 

In this way the resulting ciphertexts level with new `L` parameter will be `1` and the decryption will work.

**Comment by FrozenFort** [comment]
> > The number returned is always negative, I guess I should take its opposite as the security level, right?
> 
> No, you should assume security=0 in this case.My guess is that to get any real security with p=1031 you will need m to be at least in the 60000 to 80000 range, maybe more.
> 
> > Where do the 7,2 and 110 come from ?
> 
> Appendix C in http://eprint.iacr.org/2012/099

So does the return value of the function FHEcontext::securityLevel() indicate the security level of the AES with such key length? If not, how to translate this security level to AES key length?

**Comment by boev** [comment]
I assume the security in bits simply represents that Attacker's brute force () would require **2^security** tries. To better explain this lets consider and exhaustive search on AES key. In this case we try all keys which gives us: AES-128 having 128 bit security and AES-256 having 256 bit security. 
This however is misleading, as AES-128 and AES-256 are different (for efficiency and other reasons). Symmetric encryption is also normally cracked not by exhaustively searching the key space, but by finding weaknesses in the rounds-algorithm. So basically AES-128 has 128 bis security level under the assumptions that the underlying round algorithm is perfect (has no weaknesses).
With this said, the security parameter is the metric telling how much computation an exhaustive search would require to crack the encryption.

**Comment by boev** [comment]
And the exhaustive search bit security corresponds to real-world security for HElib under the assumptions that:
1. There are no implementation weaknesses.
2. Hardness of RLWE for BGV (AGCD for CKKS?)

**Comment by faberga** [comment]
Closing as all the questions have been answered.
