### ISSUE TITLE
Ctxt::findBaseSet warning: already at lowest level

### ISSUE THREAD

**Issue by crazyIceChen** [homenc/HElib#84]
i don't konw how i should do,when i decrypt ,Ctxt::findBaseSet warning: already at lowest level
this is my parameters long p = 2,r = 1,d = 1,c = 2,k = 80,w = 64,L = 6,m = 7; If I have a problem parameters？

**Comment by ssmiler** [comment]
Your m is too low for security. Try function FindM to find m.

**Comment by crazyIceChen** [comment]
i try to FindM to find m,but have no avail

**Comment by crazyIceChen** [comment]
Isn't that multiplyBy Too many times，Lead to noise is too biger??

**Comment by ssmiler** [comment]
This too :) Try to change L parameter. But in any case your parameters do
not assure security.

On 3 May 2016 at 15:32, crazyIceChen <notifications@github.com> wrote:

> Isn't that multiplyBy Too many times，Lead to noise is too biger??
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/shaih/HElib/issues/84#issuecomment-216528329>
>



-- 
Sergiu Carpov

**Comment by crazyIceChen** [comment]
thank you ,I have already solved ，change L 👍

**Comment by fionser** [comment]
@crazyIceChen I hope you can be careful about the choice of `m`; since "the larger `m`, the more `secure` you can get " is not 100% correct. What matter is the euler function of `m`, i.e., `phi(m)` needs to be large enough.

**Comment by faberga** [comment]
Closing as questions answered and resolved.
