### ISSUE TITLE
when nlsots = 1,readContextBase is error?

### ISSUE THREAD

**Issue by crazyIceChen** [homenc/HElib#85]
log is 
![image](https://cloud.githubusercontent.com/assets/19168641/14984778/fea1de8e-1176-11e6-8064-5a7c549c01c2.png)
Searching for cc=']' (ascii 93), found c='?' (ascii -1)

**Comment by ssmiler** [comment]
See issue #70

**Comment by crazyIceChen** [comment]
thank you
