### ISSUE TITLE
A question about the level

### ISSUE THREAD

**Issue by quanhanyu** [homenc/HElib#93]
I set the parameters as follows:

```
long m=0, p=65537, r=1; 
long L=16; 
long c=3;
long w=64;
long d=0;
long security = 80;
ZZX G;
m = FindM(security, L, c, p, d, 0, 0);
```

and I thought I can do 16 successive multiplications since L = 16. Then I set a plaintext pt = 1, and encrypted it to get a ciphertext ct. However, after I multiplied ct by itself by 7 times, the decrypted result wasn't equal to 1. The following is the test codes and the for loop breaks when i = 6. 

```
ZZX pt;
pt = 1;

Ctxt ct(publicKey);
publicKey.Encrypt(ct, pt);

Ctxt tmp = ct;
for (int i = 0; i < L; ++i) {        
    ct *= tmp;

    ZZX result;
    secretKey.Decrypt(result, ct);

    if (result != pt) {
        cout << i << endl;
        break;
    }
}
```

So I'm confused what the meaning of level is and how should I set it to get the exact multiplication depth I want. Thank you!

**Comment by fionser** [comment]
Actually this is a hard question, the increasing manner of noises in a ciphertext is quite complicated. 
For me, I have to do some trial-and-fails to get the enough level parameter L. Perhaps, you should think L as a noise-capacity, and lots of things will consume this capacity: the way you multiply (e.g, `a*=b` is different from `a.multiplyBy(b)` ); etc.,

**Comment by qdm12** [comment]
@qhyhyl In my case, I developed binary circuits able to use N bits and i.e. the multiplication of 2 binary numbers required a level L not proportional to the number of bits of the numbers, so I used linear regression on several trial&error findings of L to have a function to determine L as a function of the number of bits. 
@fionser Thanks for the information! By the way, how's a *= b different than a.multiplyBy(b)?

**Comment by fionser** [comment]
@qdm12, `*=` is some kind of low-level routine.
Actually, `.multiplyBy` is equivalent to `*=` follows by a `relinearization` (reducing the dimension of the resulting ciphertext).

**Comment by harika-n** [comment]
Can anyone please elaborate on predicting the value of L, for a set of operations on ciphertext(s)?
As written by @fionser , if we think of L as noise capacity, is it defined for each ciphertext or defined globally for all ciphertexts in a program?

**Comment by qdm12** [comment]
The best way for the best performance is with trial and error. So you just need to find the minimal L parameter without getting errors. As you do more operations (especially multiplications), you will have to increase the parameter level L. On the other hand, as you suggested maybe, if you have the ciphertexts c1, c2, c3, c4 and you do c1 = c1*c2 and c3=c3*c4 then that's only equivalent to two multiplications in terms of parameter level L. And yes the level parameter is defined for all the ciphertexts that you process (with the same keypair obviously). 
Now, you can also see that the number of homomorphic multiplications required is kind of proportional (not totally thought) to the minimum level parameter, so you could eventually use some linear regression of some kind to predict a starting point, but then again, you should test it and find the best value manually from that point. Good luck !
