### ISSUE TITLE
Aborted (core dumped) error on running AES

### ISSUE THREAD

**Issue by mostafaBio** [homenc/HElib#94]
I tried to run AES implementation but I have "the core dumped" problem happened in the line "secretKey.GenSecKey(64);" .
./Test_AES_x
**\* Test_AES: c=3, L=46, B=23, boot=0, packed=1, m=771 (=[771]), gens=[5], ords=[-32]
computing key-independent tables...done in 0.048 seconds
  32 primes (23 ctxt/9 special), total bitsize=610.982, security level: -105.818
  32 slots (2 blocks) per ctxt
computing key-dependent tables...
 before secret key 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

All the other testing files working well and contain this line.
I do not have any interpretation for this.
Please, Could you help me?
Thanks in advance

**Comment by lumip** [comment]
I noticed the same error. If I remove the "-std=c++11" flag in src/aes/Makefile and rebuild , ./Test_AES_x seems to run fine. No changes to anything else. Can you check if that solves it for you, too?

**Comment by mostafaBio** [comment]
Thanks so much lumpi. It works now. I appreciate your response.

**Comment by victorshoup** [comment]
Great! This most likely means there is no real bug here.
